# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://localhost:3001/api/entity/meta/person
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:3001/api/entity/instance/64FA60509D6811E8BFADE5B8C5C70BD8
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:3001/api/relation/meta/r_user
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:3001/api/relation/meta/entity/person
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:3001/api/entity/entityIDs
Accept: */*
Cache-Control: no-cache

###

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "relation": "r_user",
  "projection": [
    "USER_ID",
    "USER_NAME",
    "GIVEN_NAME",
    {"fieldName": "COMPANY_ID", "alias": "Company", "relation": "r_employee"}
  ],
  "filter": [
    {
      "fieldName": "USER_ID",
      "operator": "BT",
      "low": "DH002",
      "high": "DH006"
    },
    {
      "fieldName": "LANGUAGE",
      "operator": "EQ",
      "relation": "r_personalization",
      "low": "ZH"
    }
  ]
}

###

GET http://localhost:3001/api/model/entity-type/list?term=people
Accept: */*
Cache-Control: no-cache

###

GET http://www.sapmoc.com/spq/mobile/parking/getList/PVG06 HTTP/1.1
Accept: */*
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16A404 MicroMessenger/6.7.3(0x16070321) NetType/WIFI Language/zh_CN
Cookie: JSESSIONID=5C1AA7FEA5F3152C77CEEA5305AD4837

###

GET http://www.sapmoc.com/spq/mobile/parking/getEntry HTTP/1.1
Accept: */*
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16A404 MicroMessenger/6.7.3(0x16070321) NetType/WIFI Language/zh_CN
Cookie: JSESSIONID=5C1AA7FEA5F3152C77CEEA5305AD4837

###
